version: "3.9"
services:
  postgres:
    container_name: songs.postgres
    image: postgres:15
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U dev -d dev'"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s
  migrations-up:
    container_name: songs.migrations-up
    build:
      context: .
      dockerfile: dockerfile.migrations
    volumes:
      - ./migrations:/app/migrations
    environment:
      - GOOSE_DRIVER=${GOOSE_DRIVER}
      - GOOSE_DBSTRING=${GOOSE_DBSTRING}
    command: ["goose", "-dir", "migrations", "up"]
    depends_on:
      postgres:
        condition: service_healthy
  migrations-down:
    container_name: songs.migrations-down
    build:
      context: .
      dockerfile: dockerfile.migrations
    volumes:
      - ./migrations:/app/migrations
    environment:
      - GOOSE_DRIVER=${GOOSE_DRIVER}
      - GOOSE_DBSTRING=${GOOSE_DBSTRING}
    command: ["goose", "-dir", "migrations", "reset"]
    profiles:
      - migrations-down
    depends_on:
      postgres:
        condition: service_healthy
  api-up:
    container_name: songs.api
    hostname: api
    environment:
      - API_PORT=${API_PORT}
      - POSTGRES_DSN=${POSTGRES_DSN}
    image: donskova1ex/api:latest
    depends_on:
      - migrations-up
    ports:
      - 8080:${API_PORT}
