// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Music info
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 */

package openapi




type SongDetail struct {

	ReleaseDate string `json:"releaseDate"`

	Text string `json:"text"`

	Link string `json:"link"`
}

// AssertSongDetailRequired checks if the required fields are not zero-ed
func AssertSongDetailRequired(obj SongDetail) error {
	elements := map[string]interface{}{
		"releaseDate": obj.ReleaseDate,
		"text": obj.Text,
		"link": obj.Link,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSongDetailConstraints checks if the values respects the defined constraints
func AssertSongDetailConstraints(obj SongDetail) error {
	return nil
}
